##########
# Gernal #
##########

# Numbering
set -g base-index 1
set -g pane-base-index 1

# History settings
set -g history-limit 10000

##############
# Keybinding #
##############

# Unbind anything
unbind-key -a

# Open command prompt
bind-key : command-prompt

# Set key layout
set -g status-keys vi
setw -g mode-keys vi
setw -g monitor-activity on

# Color setting
set -g default-terminal "tmux-256color"

# Set prefix
unbind C-b
set -g prefix M-Space
bind M-Space send-prefix

# Mouse off
set -g mouse off

# Refresh
bind-key r refresh-client \; display-message "Client refreshed"

# Reload config
bind-key R source-file ~/.tmux.conf \; display-message "Config reloaded"

# Copy mode
bind-key v copy-mode \; display-message "Visual Mode"

# Use xclipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -sel clip > /dev/null"
bind-key p run "xclip -o -sel clip | tmux load-buffer - ; tmux paste-buffer"
bind-key -n M-p run "xclip -o -sel clip | tmux load-buffer - ; tmux paste-buffer"

# Switch layout
bind-key s command-prompt -p "Select layout:"  "select-layout '%%'"
bind-key -n M-S next-layout

# Renumber windows
set -g renumber-windows on

# Create window / pane
bind-key c new-window
bind-key x split-window
bind-key y split-window -h
bind-key t split-window -p 20
bind-key -n M-Enter split-window -h

# Movement between panes
bind-key -n M-l select-pane -R
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-h select-pane -R

# Swap panes
bind-key -n M-J swap-pane -D
bind-key -n M-K swap-pane -U
bind-key -n M-H select-pane -L \; swap-pane -s '!'
bind-key -n M-L select-pane -R \; swap-pane -s '!'
# bind-key -n M-L swap-pane -s {right-of}
# bind-key -n M-H swap-pane -s {left-of}

# Switch windows
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
bind-key -n M-0 select-window -t 10
bind-key -n M-Tab select-window -t:+1

# Move current pane to window
bind-key -n M-'!' join-pane -t :1
bind-key -n M-'@' join-pane -t :2
bind-key -n M-'#' join-pane -t :3
bind-key -n M-'$' join-pane -t :4
bind-key -n M-'%' join-pane -t :5
bind-key -n M-'^' join-pane -t :6
bind-key -n M-'&' join-pane -t :7
bind-key -n M-'*' join-pane -t :8
bind-key -n M-'(' join-pane -t :9
bind-key -n M-')' join-pane -t :10

# Resize panes
bind-key -n M-Down resize-pane -D 5
bind-key -n M-Up resize-pane -U 5
bind-key -n M-Left resize-pane -L 5
bind-key -n M-Right resize-pane -R 5

########
# Look #
########

# Status
set -g status-style none
set -g status-fg white
set -g status-bg default
set -g status-interval 5
set -g status-position bottom
set -g status-justify centre

set -g status-left ''
set -g status-right ''

set -g window-status-activity-style none
set -g window-status-format '#{?window_activity_flag,#[fg=red#,bg=black],#[fg=white#,bg=black]} #I: #W #[default]'
set -g window-status-current-format '#[fg=black,bg=green] #I: #W #[default]'
set -g window-status-separator '  '

# Border
set -g pane-border-style bg=default
set -g pane-border-style fg=white
set -g pane-active-border-style bg=default
set -g pane-active-border-style fg=yellow

#########
# Other #
#########

# No delay for escape key press
set -sg escape-time 0
