dictionaries = [
    "en_us",
    "en_gb",
    "de",
]

words = []

flag_words = ["todo", "fixme"]

ignore_paths = [
    "target/**/*",
]

ignore_patterns = [
    'https?://[^\s]+',
]

include_tags = ["comment", "string"]
